Document: lua-zlib
Title: Debian lua-zlib Manual
Author: <insert document author here>
Abstract: This manual describes what lua-zlib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lua-zlib/lua-zlib.sgml.gz

Format: postscript
Files: /usr/share/doc/lua-zlib/lua-zlib.ps.gz

Format: text
Files: /usr/share/doc/lua-zlib/lua-zlib.text.gz

Format: HTML
Index: /usr/share/doc/lua-zlib/html/index.html
Files: /usr/share/doc/lua-zlib/html/*.html
